"""Add ABAC fields

Revision ID: 781eb93bc1e9
Revises: a4c8adeae340
Create Date: 2026-06-25 18:00:15.213874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '781eb93bc1e9'
down_revision: Union[str, Sequence[str], None] = 'a4c8adeae340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('city', sa.String(), nullable=True))
    op.add_column('users', sa.Column('ward', sa.String(), nullable=True))
    op.add_column('users', sa.Column('department', sa.String(), nullable=True))
    op.add_column('users', sa.Column('region', sa.String(), nullable=True))
    op.add_column('users', sa.Column('clearance_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'clearance_level')
    op.drop_column('users', 'region')
    op.drop_column('users', 'department')
    op.drop_column('users', 'ward')
    op.drop_column('users', 'city')
    # ### end Alembic commands ###
