"""Add encrypted columns to user

Revision ID: a4c8adeae340
Revises: 6e159bb6f97d
Create Date: 2026-06-25 17:58:01.271307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4c8adeae340'
down_revision: Union[str, Sequence[str], None] = '6e159bb6f97d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('government_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('personal_notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'personal_notes')
    op.drop_column('users', 'government_id')
    # ### end Alembic commands ###
